# Generated by Django 2.2.4 on 2019-08-15 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=128)),
                ('nickname', models.CharField(max_length=128)),
                ('create_time', models.DateTimeField()),
                ('user_type', models.CharField(max_length=64)),
                ('permission', models.CharField(default='normal', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('software', models.CharField(max_length=64)),
                ('access_ip', models.CharField(max_length=64)),
                ('device_type', models.CharField(max_length=64)),
                ('access_time', models.DateTimeField()),
                ('code', models.CharField(max_length=128)),
                ('state', models.CharField(max_length=64)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='oauth.User')),
            ],
        ),
        migrations.CreateModel(
            name='AppScheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('level', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('tags', models.TextField()),
                ('appKey', models.CharField(max_length=256)),
                ('state', models.CharField(max_length=64)),
                ('admins', models.ManyToManyField(related_name='admin_apps', to='oauth.User')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apps', to='oauth.User')),
            ],
        ),
    ]
