# Generated by Django 2.2.4 on 2019-08-18 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='access_id',
            field=models.CharField(default='', max_length=64),
        ),
    ]
