# Generated by Django 2.2.4 on 2019-08-18 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0002_useractivity_access_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'student'), (1, 'teacher'), (2, 'others')], max_length=64),
        ),
    ]
