# Generated by Django 2.2.4 on 2019-08-18 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0004_auto_20190818_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='permission',
            field=models.PositiveSmallIntegerField(choices=[(0, 'normal'), (1, 'admin'), (2, 'superadmin')], default=0),
        ),
    ]
