# Generated by Django 2.2.4 on 2019-08-18 15:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0005_auto_20190818_2220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appscheme',
            old_name='appKey',
            new_name='appkey',
        ),
        migrations.RemoveField(
            model_name='appscheme',
            name='admins',
        ),
        migrations.AddField(
            model_name='appscheme',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appscheme',
            name='title',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='appscheme',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='appscheme',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(0, 'third'), (1, 'auth')], default=0),
        ),
        migrations.AlterField(
            model_name='appscheme',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(0, 'wait'), (1, 'success'), (2, 'fail')], default=0),
        ),
        migrations.AlterField(
            model_name='appscheme',
            name='tags',
            field=models.TextField(default=''),
        ),
        migrations.CreateModel(
            name='AppPer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=256)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='own_pers', to='oauth.AppScheme')),
            ],
        ),
    ]
