# Generated by Django 2.2.4 on 2019-08-19 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0006_auto_20190818_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(0, 'success'), (1, 'fail'), (2, 'banned')], default=0),
        ),
    ]
