# Generated by Django 2.2.4 on 2019-08-22 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0007_auto_20190819_0902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appscheme',
            name='level',
        ),
        migrations.DeleteModel(
            name='AppPer',
        ),
    ]
