# Generated by Django 2.2.4 on 2019-08-25 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0008_auto_20190822_1027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='code',
            field=models.CharField(default='', max_length=128),
        ),
    ]
